### ISSUE TITLE
Windows compatibility

### ISSUE THREAD

**Issue by Goheeca** [sellout/external-program#20] opened 2015-01-28 13:13 UTC
In SBCL implementation external-program is looking for /usr/bin/env which is nonexistent in Windows.

**Comment by spaceotter** [comment] 2015-02-16 10:51
I just tried to load cl-ana on Windows which uses external-program for gnuplot, and ran into this problem. This is probably bad on GNU/Linux too, as it assumes env is in /usr/bin and not /bin or somewhere else. If it used the %PATH% it could at least find the Cygwin env on Windows.

**Comment by eudoxia0** [comment] 2015-11-14 21:12
Any plans to fix this? I'd use UIOP for portability, but I need a way to get the process object.

**Comment by Shinmera** [comment] 2015-11-27 22:54
The problem is that it's using the `windows` feature test which is non-standard. It should depend on `trivial-features` to provide that.

**Comment by pipping** [comment] 2016-07-29 22:56
This was fixed in 04b4ace, no? (except for the non-standard feature test)

**Comment by pipping** [comment] 2016-08-07 10:21
@eudoxia0 What running an (asynchronous) external project gives you differs dramatically by platform. CLISP gives you nothing. LispWorks gives you a stream. Others give you a PID. And `uiop/run-program::%run-program` does make that available as the `:process` field in the plist it returns. What do you want to do with the process object anyway?

**Comment by pipping** [comment] 2016-08-07 10:24
Fixed with a7af2ef1aab1f7d01de40c27a69c3bf495e6e9c3.

**Closed by pipping** 2016-08-07 10:24 UTC
